#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=01

start_service() {
	/usr/sbin/tailscaled --cleanup

	procd_open_instance
	procd_set_param command /usr/sbin/tailscaled

# Set the port to listen on for incoming VPN packets.
# Remote nodes will automatically be informed about the new port number,
# but you might want to configure this in order to set external firewall
# settings.
	procd_append_param command --port 41641

# OpenWRT /var is a symlink to /tmp, so write persistent state elsewhere.
	procd_append_param command --state /etc/tailscale/tailscaled.state

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

stop_service() {
	/usr/sbin/tailscale down
	/usr/sbin/tailscaled --cleanup
}

