#!/bin/sh
SCRIPT="$(basename $0)"

usage() {
cat <<EOH

Usage: $0 [options]

Options:
 -U  Download the latest version of $SCRIPT from GitHub

EOH
exit
}

upgrade() {
  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/UncleSam1966/tch-tailscale/master/$SCRIPT)
  if [ "$RESPONSE_CODE" = 200 ];then
    curl -kL -o $SCRIPT https://raw.githubusercontent.com/UncleSam1966/tch-tailscale/master/$SCRIPT
    if [ $? -eq 0 ];then
      chmod +x $SCRIPT
      echo "[Tailscale-Regress] Successfully downloaded $SCRIPT."
    else
      echo "[Tailscale-Regress] Failed to download $SCRIPT."
    fi
  elif [ "$RESPONSE_CODE" = 404 ];then
    echo "[Tailscale-Regress] ERROR! Not found on GitHub???"
  elif [ "$RESPONSE_CODE" = 000 ];then
    echo "ERROR! No Internet connection???"
  else
    echo "[Tailscale-Regress] ERROR! Unknown response code $RESPONSE_CODE"
  fi
  exit
}

while getopts :U option; do
 case "${option}" in
  U)  upgrade;;
  *)  usage;;
 esac
done
shift $((OPTIND-1))

echo 
echo "Installs the previous release of Tailscale."
echo 
echo "If you wish to proceed, enter y otherwise just press [Enter] to stop: "
echo 
read REPLY
if [ "$REPLY" != "y" -a "$REPLY" != "Y" ]; then
#  rm ./runonce
      echo "[Tailscale-Regress] Regression aborted."
	  echo 
  exit
fi

# check the version of the installed Tailscale
echo "[Tailscale-Regress] Getting installed Tailscale version..."
CURRENT=$(/usr/sbin/tailscale --version | head -n 1)
[ -z "$CURRENT" ] && { echo "[Tailscale-Regress] ERROR! Could not determine current Tailscale version. Aborting..."; exit 2; }
echo "[Tailscale-Regress] Installed Tailscale version is $CURRENT"

# Check the previous version of Tailscale
echo "[Tailscale-Regress] Getting previous Tailscale version..."
PREVIOUS=$(curl -ks https://tailscale.com/changelog/#client | awk '/<a id="/{print $3;}0' | head -n 2 | tail -n 1 | cut -c2-)
[ -z "$PREVIOUS" ] && { echo "[Tailscale-Regress] ERROR! Could not determine previous Tailscale version. Aborting..."; exit 2; }
echo "[Tailscale-Regress] previous Tailscale version is $PREVIOUS"

  case "$(uname -m)" in
    aarch64)  ARCH="arm64";;
    armv7l)   ARCH="arm";;
    *)        echo "[Tailscale-Regress] ERROR! Unable to handle $(uname -m) archictecture! Aborting..."; exit 2;;
  esac
  FILENAME="tailscale_${PREVIOUS}_${ARCH}.tgz"
  DIRNAME="tailscale_${PREVIOUS}_${ARCH}"
  URL="https://pkgs.tailscale.com/stable/$FILENAME"

  cd /tmp
  echo "[Tailscale-Regress] Downloading $URL"
  curl -kLSO "$URL"
  echo "[Tailscale-Regress] Extracting $FILENAME into /tmp"
  tar -zxf "$FILENAME"
  cd /usr/sbin
  echo "[Tailscale-Regress] Stopping Tailscale $CURRENT..."
  /etc/init.d/tailscale stop > /dev/null 2>&1
  echo "[Tailscale-Regress] Regressing Tailscale to $PREVIOUS..."
  cp "/tmp/$DIRNAME/tailscale" .
  cp "/tmp/$DIRNAME/tailscaled" .
  echo "[Tailscale-Regress] Starting Tailscale..."
  /etc/init.d/tailscale start > /dev/null 2>&1
  echo "[Tailscale-Regress] Cleaning up..."
  rm -rf "/tmp/$FILENAME" "/tmp/$DIRNAME" 

echo "[Tailscale-Regress] Done!"
